name: daily-traffic-data-fetching


on:
  schedule:
  - cron:  '1 0 * * * *'

jobs:
  fetch-traffics:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install
      run: npm install
      working-directory: ./backend
    - name: fetch
      run: node scripts/dailyGetTraffics.js
      env:
        awsAccessKeyId: ${{ secrets.awsAccessKeyId }}
        awsSecretAccessKey: ${{ secrets.awsSecretAccessKey }}
      working-directory: ./backend
