name: daily-traffic-data-fetching

on:
  schedule:
  - cron:  '*/2 * * * *'

jobs:
  fetch-traffics:
    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install and fetch
      run: |
        cd backend
        npm ci
        node scripts/dailyGetTraffics.js
